### RandomForest
- 집단 학습을 기반으로 고정밀 분류, 회귀, 클러스터링 등을 구현
- 학습 전용 데이터를 기반으로 다수의 의사결정트리를 만들고 만들어진 의사결정트리를 기반으로 다수 결과를 유도하는 모델
- Ensemble(앙상블) 기법의 지표가 됨

In [1]:
import pandas as pd

In [3]:
iris = pd.read_csv("../Data/iris.csv")
iris.head()

   SepalLength  SepalWidth  PetalLength  PetalWidth         Name
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [6]:
# Feature와 Target 분리
iris_data = iris[['SepalLength', 'SepalWidth','PetalLength', 'PetalWidth']]
iris_target = iris['Name']

In [7]:
# 확인
print(iris_data.shape)
print(iris_target.shape)

(150, 4)
(150,)

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
# Train과 Test 분리
train_data, test_data, train_target, test_target = train_test_split(
                                                        iris_data,
                                                        iris_target,
                                                        random_state=42,
                                                        stratify=iris_target
)

In [10]:
# 확인
print(train_data.shape)
print(test_data.shape)
print(train_target.shape)
print(test_target.shape)

(112, 4)
(38, 4)
(112,)
(38,)

In [11]:
# Sampling 판단
print(train_data.describe())
print(test_data.describe())

       SepalLength  SepalWidth  PetalLength  PetalWidth
count   112.000000  112.000000   112.000000  112.000000
mean      5.877679    3.061607     3.765179    1.192857
std       0.853262    0.440770     1.782584    0.771533
min       4.300000    2.000000     1.100000    0.100000
25%       5.100000    2.800000     1.575000    0.300000
50%       5.800000    3.000000     4.300000    1.300000
75%       6.400000    3.300000     5.100000    1.825000
max       7.900000    4.400000     6.900000    2.500000
       SepalLength  SepalWidth  PetalLength  PetalWidth
count    38.000000   38.000000    38.000000   38.000000
mean      5.742105    3.031579     3.739474    1.215789
std       0.750363    0.416618     1.733071    0.747799
min       4.400000    2.300000     1.000000    0.200000
25%       5.125000    2.825000     1.700000    0.300000
50%       5.700000    3.000000     4.500000    1.400000
75%       6.375000    3.300000     5.075000    1.800000
max       7.300000    4.000000     6.300000    2.400000

In [12]:
# Target 확인
print(train_target.describe())
print(test_target.describe())

count             112
unique              3
top       Iris-setosa
freq               38
Name: Name, dtype: object
count                  38
unique                  3
top       Iris-versicolor
freq                   13
Name: Name, dtype: object

---
### RandomForest로 분류

In [13]:
from sklearn.ensemble import RandomForestClassifier

In [33]:
# 모델 만들기
clf = RandomForestClassifier(n_estimators=1) # Hyper Parameter -> n_estimators : tree 갯수

In [34]:
# 학습시키기
clf.fit(train_data, train_target)

RandomForestClassifier(n_estimators=1)

In [35]:
# 평가하기
print(clf.score(train_data, train_target))
print(clf.score(test_data, test_target))

0.9821428571428571
0.868421052631579

---
### 독버섯과 관련된 데이터를 사용한 머신러닝
- 8124종류의 버섯의 특징과 독의 유무로 구성되어 있는 데이터셋 
- 버섯의 특징을 기반으로 독의 유무를 판단

In [36]:
# 데이터 획득하기
import urllib.request as req
local = "../Data/mushroom.csv"
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/mushroom/agaricus-lepiota.data"
req.urlretrieve(url, local)
print('OK')

OK

In [38]:
mr = pd.read_csv("../Data/mushroom.csv", header=None)
mr.head()

  0  1  2  3  4  5  6  7  8  9   ... 13 14 15 16 17 18 19 20 21 22
0  p  x  s  n  t  p  f  c  n  k  ...  s  w  w  p  w  o  p  k  s  u
1  e  x  s  y  t  a  f  c  b  k  ...  s  w  w  p  w  o  p  n  n  g
2  e  b  s  w  t  l  f  c  b  n  ...  s  w  w  p  w  o  p  n  n  m
3  p  x  y  w  t  p  f  c  n  n  ...  s  w  w  p  w  o  p  k  s  u
4  e  x  s  g  f  n  f  w  b  k  ...  s  w  w  p  w  o  e  n  a  g

[5 rows x 23 columns]

In [39]:
mr.tail()

     0  1  2  3  4  5  6  7  8  9   ... 13 14 15 16 17 18 19 20 21 22
8119  e  k  s  n  f  n  a  c  b  y  ...  s  o  o  p  o  o  p  b  c  l
8120  e  x  s  n  f  n  a  c  b  y  ...  s  o  o  p  n  o  p  b  v  l
8121  e  f  s  n  f  n  a  c  b  n  ...  s  o  o  p  o  o  p  b  c  l
8122  p  k  y  n  f  y  f  c  n  b  ...  k  w  w  p  w  o  e  w  v  l
8123  e  x  s  n  f  n  a  c  b  y  ...  s  o  o  p  o  o  p  o  c  l

[5 rows x 23 columns]

In [40]:
mr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       8124 non-null   object
 1   1       8124 non-null   object
 2   2       8124 non-null   object
 3   3       8124 non-null   object
 4   4       8124 non-null   object
 5   5       8124 non-null   object
 6   6       8124 non-null   object
 7   7       8124 non-null   object
 8   8       8124 non-null   object
 9   9       8124 non-null   object
 10  10      8124 non-null   object
 11  11      8124 non-null   object
 12  12      8124 non-null   object
 13  13      8124 non-null   object
 14  14      8124 non-null   object
 15  15      8124 non-null   object
 16  16      8124 non-null   object
 17  17      8124 non-null   object
 18  18      8124 non-null   object
 19  19      8124 non-null   object
 20  20      8124 non-null   object
 21  21      8124 non-null   object
 22  22      8124 non-null   object
dtypes: object(23)
memory usage: 1.4+ MB

In [41]:
mr.shape

(8124, 23)

- 한줄이 버섯 한종류
- 첫번째 열 : p(독버섯), e(식용) --> Target
- 두번째 열 : 버섯의 머리 모양 => b(벨), c(원뿔), x(볼록), f(평평), k(혹), s(오목) 
- 네번째 열 : 버섯의 머리 색깔 => n(갈색), b(황갈색), c(연한 갈색), ...

> Feature Data를 숫자화 시킨다.

In [52]:
# 연습 : 알파벳 -> ASCII Code 변환 
print(ord('x'))

# ASCII -> 문자
print(chr(120))

120
x