### 로지스틱 회귀
: 선형방정식을 이용하여 회귀란 단어가 있지만 실제적으로 분류에 대한 확률을 계산하는 모델이다.

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd

In [3]:
fish = pd.read_csv("../Data/fishes.csv")
fish.head()

  Species  Weight  Length  Diagonal   Height   Width
0   Bream   242.0    25.4      30.0  11.5200  4.0200
1   Bream   290.0    26.3      31.2  12.4800  4.3056
2   Bream   340.0    26.5      31.1  12.3778  4.6961
3   Bream   363.0    29.0      33.5  12.7300  4.4555
4   Bream   430.0    29.0      34.0  12.4440  5.1340

In [4]:
# Target으로 사용될 Species의 종류 알아보기 
fish.Species.unique()

array(['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'],
      dtype=object)

In [5]:
# Species별 Data의 차이가 큰지 ?
fish.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Species   159 non-null    object
 1   Weight    159 non-null    float64
 2   Length    159 non-null    float64
 3   Diagonal  159 non-null    float64
 4   Height    159 non-null    float64
 5   Width     159 non-null    float64
dtypes: float64(5), object(1)
memory usage: 7.6+ KB

In [6]:
fish.describe()

            Weight      Length    Diagonal      Height       Width
count   159.000000  159.000000  159.000000  159.000000  159.000000
mean    398.326415   28.415723   31.227044    8.970994    4.417486
std     357.978317   10.716328   11.610246    4.286208    1.685804
min       0.000000    8.400000    8.800000    1.728400    1.047600
25%     120.000000   21.000000   23.150000    5.944800    3.385650
50%     273.000000   27.300000   29.400000    7.786000    4.248500
75%     650.000000   35.500000   39.650000   12.365900    5.584500
max    1650.000000   63.400000   68.000000   18.957000    8.142000

> 정규화가 필요하다.

### Feature와 Target으로 분리

In [7]:
# Feature Data : Weight, Length, Diagonal, Height, Width 만 선택하여 numpy배열로 변경 
fish_input = fish[['Weight','Length',"Diagonal","Height","Width"]].to_numpy()
fish_input[:5]

array([[242.    ,  25.4   ,  30.    ,  11.52  ,   4.02  ],
       [290.    ,  26.3   ,  31.2   ,  12.48  ,   4.3056],
       [340.    ,  26.5   ,  31.1   ,  12.3778,   4.6961],
       [363.    ,  29.    ,  33.5   ,  12.73  ,   4.4555],
       [430.    ,  29.    ,  34.    ,  12.444 ,   5.134 ]])

In [8]:
# Target Data : Species를 선택하여 numpy 배열로 변경
fish_target = fish['Species'].to_numpy()
fish_target[:5]

array(['Bream', 'Bream', 'Bream', 'Bream', 'Bream'], dtype=object)

### train과 test로 분리하기

In [9]:
from sklearn.model_selection import train_test_split
train_input, test_input, train_target, test_target = train_test_split(
                                                            fish_input,
                                                            fish_target,
                                                            random_state=42,
                                                            stratify=fish_target
)

### 표준화 시키기
: 각 컬럼별 데이터의 크기 차이가 많이 나는 경우 사용

In [13]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(train_input)
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)

In [14]:
train_scaled[:5]

array([[-0.75628803, -0.66065677, -0.62357446, -0.78015159, -0.45043644],
       [-0.45991057, -0.1248453 , -0.24414603, -0.4293487 ,  0.03516919],
       [ 0.07356886,  0.0212851 ,  0.2165885 ,  0.79541208,  0.37481797],
       [ 1.54063728,  1.0441979 ,  1.23743166,  2.29283234,  1.34130358],
       [-0.87483902, -0.75807703, -0.82232269, -0.80672937, -0.5697143 ]])

In [16]:
test_scaled[:5]

array([[-0.84520127, -0.75807703, -0.71391456, -0.70656438, -0.72566082],
       [-0.81556352, -0.72885095, -0.79522065, -0.64263534, -0.58227616],
       [-0.96375225, -0.95291757, -1.03010492, -0.82018436, -0.8716775 ],
       [-0.84520127, -0.95291757, -0.93073081, -0.16608636, -0.95069758],
       [-0.93411451, -1.07956391, -1.06624096, -0.40030299, -1.09731243]])